package com.example.cameraapp.model

data class Referencepose(
    val NOSE: PoseLandmark,
    val LEFT_EYE_INNER: PoseLandmark,
    val LEFT_EYE: PoseLandmark,
    val LEFT_EYE_OUTER: PoseLandmark,
    val RIGHT_EYE_INNER: PoseLandmark,
    val RIGHT_EYE: PoseLandmark,
    val RIGHT_EYE_OUTER: PoseLandmark,
    val LEFT_EAR: PoseLandmark,
    val RIGHT_EAR: PoseLandmark,
    val MOUTH_LEFT: PoseLandmark,
    val MOUTH_RIGHT: PoseLandmark,
    val LEFT_SHOULDER: PoseLandmark,
    val RIGHT_SHOULDER: PoseLandmark,
    val LEFT_ELBOW: PoseLandmark,
    val RIGHT_ELBOW: PoseLandmark,
    val LEFT_WRIST: PoseLandmark,
    val RIGHT_WRIST: PoseLandmark,
    val LEFT_PINKY: PoseLandmark,
    val RIGHT_PINKY: PoseLandmark,
    val LEFT_INDEX: PoseLandmark,
    val RIGHT_INDEX: PoseLandmark,
    val LEFT_THUMB: PoseLandmark,
    val RIGHT_THUMB: PoseLandmark,
    val LEFT_HIP: PoseLandmark,
    val RIGHT_HIP: PoseLandmark,
    val LEFT_KNEE: PoseLandmark,
    val RIGHT_KNEE: PoseLandmark,
    val LEFT_ANKLE: PoseLandmark,
    val RIGHT_ANKLE: PoseLandmark,
    val LEFT_HEEL: PoseLandmark,
    val RIGHT_HEEL: PoseLandmark,
    val LEFT_FOOT_INDEX: PoseLandmark,
    val RIGHT_FOOT_INDEX: PoseLandmark
)